### ISSUE TITLE
DLL loads if in Pal/Binaries/Win64, but doesn't load config if EXE is inaccessible.

### ISSUE THREAD

**Issue by StrikerTheHedgefox** [palworld-admin/server#1]
I have a palworld server hosted through GPortal, but they block access to the EXE path. The DLL loads perfectly fine if you place it in Pal/Binaries/Win64, but it can't load the config file, since the EXE is located elsewhere. Could you perhaps have it look specifically in that path? (or maybe relative to the DLL location, rather than EXE).

**Comment by t4bby** [comment]
Hello,

Could you give a possible directory of the `Pal/Binaries/Win64` when you host the game. I'll add a check if the config exists in that folder.

**Comment by StrikerTheHedgefox** [comment]
Like the absolute directory of the server relative to drive root? Since this is on a hosting service, I don't have access to that information. But, this is the folder structure on the server's FTP. (I know d3d9.dll is missing here. I have it removed temporarily.) ![image](https://shadowmavericks.com/files/ShareX/explorer_2024-01-31_00-36-56.png)

Stuff like UE4SS works, so that gives me hope that it may be possible to read the config in that path somehow, even if the EXE isn't in there.

**Comment by t4bby** [comment]
I've added a patch that will load the `palworld-admin.config.json` where you can find the `d3d9.dll`

Preview: https://github.com/palworld-admin/server/releases/tag/0.0.2

**Comment by StrikerTheHedgefox** [comment]
Excellent. Thank you.
